apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cupp-output-pvc
  namespace: cupp-v2
  labels:
    app: cupp-v2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
