apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credweaver-output-pvc
  namespace: credweaver
  labels:
    app: credweaver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
